version: "3"

networks:
  service-network:

services:
  web:
    image: mousai86/hostname:latest
    ports:
      - "80:80"
    networks:
      - service-network
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
